#!/bin/sh

source /opt/config/mod/.shell/0.sh

unset LD_PRELOAD

start() {
  /etc/init.d/prepare.sh &
}

stop() {
    printf "Stopping moon: "
    [ ${FF5X} -eq 0 ] && umount ${UMOUNT_MOD}
    chroot ${MOD} /opt/config/mod/.shell/root/stop.sh
    [ ${FF5X} -eq 0 ] && mount --bind ${REMOUNT_MOD} ${UMOUNT_MOD}
    echo "OK"
}

up() {
    printf "Starting moon: "
    [ ${FF5X} -eq 0 ] && umount ${UMOUNT_MOD}
    chroot ${MOD} /opt/config/mod/.shell/root/start.sh &
    sleep 15
    [ ${FF5X} -eq 0 ] && mount --bind ${REMOUNT_MOD} ${UMOUNT_MOD}
    echo "OK"
}

case "$1" in
    up)
        up
        ;;
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|up}"
        exit 1
esac

exit $?
